export default {
    1:{
        img:require('../images/charts/line.png'),
        text:"折线图"
    },
    2:{
        img:require('../images/charts/bar.png'),
        text:"折线图"
    },
    3:{
        img:require('../images/charts/bar_r.png'),
        text:"条形图"
    },
    4:{
        img:require('../images/charts/bar_rc.png'),
        text:"对比条形图"
    },
    5:{
        img:require('../images/charts/radar.png'),
        text:"雷达图"
    },
    6:{
        img:require('../images/charts/doubleaxis.png'),
        text:"双轴图"
    },
    7:{
        img:require('../images/charts/area.png'),
        text:"面积图"
    },
    8:{
        img:require('../images/charts/relation.png'),
        text:"关系图"
    },
    9:{
        img:require('../images/charts/tree.png'),
        text:"树状图"
    },
    10:{
        img:require('../images/charts/funnel.png'),
        text:"漏斗图"
    },
    11:{
        img:require('../images/charts/sankey.png'),
        text:"桑基图"
    },
    12:{
        img:require('../images/charts/map.png'),
        text:"地图"
    },
    13:{
        img:require('../images/charts/dots.png'),
        text:"散点图"
    },
    14:{
        img:require('../images/charts/bubble.png'),
        text:"气泡图"
    },
    15:{
        img:require('../images/charts/heatmap.png'),
        text:"热力图"
    },
    16:{
        img:require('../images/charts/words.png'),
        text:"词云"
    },
    17:{
        img:require('../images/charts/pie.png'),
        text:"饼图"
    },
    18:{
        img:require('../images/charts/ring.png'),
        text:"环形图"
    },
    19:{
        img:require('../images/charts/nightingale.png'),
        text:"南丁格尔图"
    },
    20:{
        img:require('../images/charts/ring_n.png'),
        text:"嵌套环形图"
    },
    21:{
        img:require('../images/charts/bar_s.png'),
        text:"堆积柱状图"
    },
    22:{
        img:require('../images/charts/bar_p.png'),
        text:"百分比柱状图"
    },
    23:{
        img:require('../images/charts/bar_rs.png'),
        text:"堆积条形图"
    },
    24:{
        img:require('../images/charts/bar_rp.png'),
        text:"百分比条形图"
    },
    25:{
        img:require('../images/charts/line_s.png'),
        text:"堆积面积图"
    },
    26:{
        img:require('../images/charts/line_p.png'),
        text:"百分比堆积面积图"
    },
    27:{
        img:require('../images/charts/waterfall.png'),
        text:"阶梯瀑布图"
    },
    28:{
        img:require('../images/charts/treemap.png'),
        text:"矩形树图"
    },
    29:{
        img:require('../images/charts/table.png'),
        text:"表格"
    },
    30:{
        img:require('../images/charts/kpi.png'),
        text:"KPI"
    },
    31:{
        img:require('../images/charts/calculate.png'),
        text:"仪表盘"
    }
}